componentScriptContent: 
  - xmlizable: 
    - ‚Üëclassname: com.twinsoft.convertigo.beans.common.FormatedContent
    - com.twinsoft.convertigo.beans.common.FormatedContent: 
      ‚Üí: |
        /*Begin_c8o_AppImport*/
        /*End_c8o_AppImport*/
        /*Begin_c8o_AppDeclaration*/
        	/*End_c8o_AppDeclaration*/
        /*Begin_c8o_AppConstructor*/
        		/*End_c8o_AppConstructor*/
        /*Begin_c8o_AppInitialization*/
                        /* Uncomment the following lines to enable the i18n feature.
                         * You should add a json per language in the assets/i18n folder. */
                        translate.setDefaultLang('en');
                        translate.use(translate.getBrowserLang());
                        
                        /* Uncomment the following lines to enable the custom status bar color. */
                        // statusBar.overlaysWebView(false);
                        // statusBar.backgroundColorByHexString("#000000");
                        // statusBar.styleBlackOpaque();
        			/*End_c8o_AppInitialization*/
        /*Begin_c8o_AppFunction*/
        	/*End_c8o_AppFunction*/
        
tplProjectName: mobilebuilder_tpl_7_8_0
‚ÜìMenu [mobile.components.UIDynamicMenu-1500890597895]: üóè mobileMenus/Menu.yaml
‚ÜìcardIO_sa [mobile.components.UIActionStack-1595431416100]: üóè mobileSharedActions/cardIO_sa.yaml
‚ÜìZXing_sa [mobile.components.UIActionStack-1595431416151]: üóè mobileSharedActions/ZXing_sa.yaml
‚ÜìagGrid [mobile.components.UISharedComponent-1576501532114]: üóè mobileSharedComponents/agGrid.yaml
‚ÜìngxTagInput [mobile.components.UISharedComponent-1577113184271]: üóè mobileSharedComponents/ngxTagInput.yaml
‚ÜìtinyMce [mobile.components.UISharedComponent-1584094766586]: üóè mobileSharedComponents/tinyMce.yaml
‚ÜìangularxQRCode [mobile.components.UISharedComponent-1600099015160]: üóè mobileSharedComponents/angularxQRCode.yaml
‚ÜìcardIO_sc [mobile.components.UISharedComponent-1595431403877]: üóè mobileSharedComponents/cardIO_sc.yaml
‚ÜìtestAgGrid1 [mobile.components.PageComponent-1577112296926]: üóè mobilePages/testAgGrid1.yaml
‚ÜìtestAgGrid2 [mobile.components.PageComponent-1500538678074]: üóè mobilePages/testAgGrid2.yaml
‚ÜìtestNgxInput [mobile.components.PageComponent-1577114040810]: üóè mobilePages/testNgxInput.yaml
‚ÜìtestNgxInput1 [mobile.components.PageComponent-1578565185309]: üóè mobilePages/testNgxInput1.yaml
‚ÜìcardIO [mobile.components.PageComponent-1595431440350]: üóè mobilePages/cardIO.yaml
‚ÜìZXing [mobile.components.PageComponent-1595431440486]: üóè mobilePages/ZXing.yaml
‚ÜìTheme [mobile.components.UITheme-1491635018260]: 
  comment: Global color themes can be customized here
  styleContent: 
    - xmlizable: 
      - ‚Üëclassname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        ‚Üí: |
          '// Ionic Variables and Theming. For more info, please see:
          // http://ionicframework.com/docs/v2/theming/ 
          $font-path: "../assets/fonts";
          
          @import "ionic.globals";
          
          
          // Shared Variables
          // --------------------------------------------------
          // To customize the look and feel of this app, you can override
          // the Sass variables found in Ionic''s source scss files.
          // To view all the possible Ionic variables, see:
          // http://ionicframework.com/docs/v2/theming/overriding-ionic-variables/
          
          
          
          
          // Named Color Variables
          // --------------------------------------------------
          // Named colors makes it easy to reuse colors on various components.
          // It''s highly recommended to change the default colors
          // to match your app''s branding. Ionic uses a Sass map of
          // colors so you can add, rename and remove colors as needed.
          // The "primary" color is the only required color in the map.
          
          $colors: (
                  primary:    #387ef5,
                  secondary:  #32db64,
                  danger:     #f53d3d,
                  light:      #f4f4f4,
                  dark:       #222
          );
          
          
          // App iOS Variables
          // --------------------------------------------------
          // iOS only Sass variables can go here
          
          
          
          
          // App Material Design Variables
          // --------------------------------------------------
          // Material Design only Sass variables can go here
          
          
          
          
          // App Windows Variables
          // --------------------------------------------------
          // Windows only Sass variables can go here
          
          
          
          
          // App Theme
          // --------------------------------------------------
          // Ionic apps can have different themes applied, which can
          // then be future customized. This import comes last
          // so that the above variables are used and Ionic''s
          // default are overridden.
          
          @import "ionic.theme.default";
          @import "../../node_modules/ag-grid-community/dist/styles/ag-grid.scss";
          @import "../../node_modules/ag-grid-community/dist/styles/ag-theme-balham/sass/ag-theme-balham.scss";
          
          // Ionicons
          // --------------------------------------------------
          // The premium icon font for Ionic. For more info, please see:
          // http://ionicframework.com/docs/v2/ionicons/
          
          @import "ionic.ionicons";
          
          
          // Fonts
          // --------------------------------------------------
          
          @import "roboto";
          @import "noto-sans";
          '
‚ÜìAgGridStyle [mobile.components.UIStyle-1607860511221]: 
  comment: You can add some global application styles here
  styleContent: 
    - xmlizable: 
      - ‚Üëclassname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        ‚Üí: |
          '.custom-header-weel {
          	background-image: url(data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7);
          	background-repeat: no-repeat;
          	background-position: center;
          }
          @import "../../node_modules/ag-grid-community/dist/styles/ag-grid.scss";
          @import "../../node_modules/ag-grid-community/dist/styles/ag-theme-balham/sass/ag-theme-balham.scss";
          '